#include "ins_names.h"

const char *MidiInsName[128] =
{
    "Acoustic Grand Piano",
    "Bright Acoustic Piano",
    "Electric Grand Piano",
    "Honky-tonkPiano",
    "Rhodes Piano",
    "Chorused Piano",
    "Harpsichord",
    "Clavinet",
    "Celesta",
    "Glockenspiel",
    "Music box",
    "Vibraphone",
    "Marimba",
    "Xylophone",
    "Tubular Bells",
    "Dulcimer",
    "Hammond Organ",
    "Percussive Organ",
    "Rock Organ",
    "Church Organ",
    "Reed Organ",
    "Accordion",
    "Harmonica",
    "Tango Accordion",
    "Acoustic Guitar (nylon)",
    "Acoustic Guitar (steel)",
    "Electric Guitar (clean)",
    "Electric Guitar (jazz)",
    "Electric Guitar (muted)",
    "Overdrive Guitar",
    "Distorton Guitar",
    "Guitar Harmonics",
    "Acoustic Bass",
    "Electric Bass (finger)",
    "Electric Bass (pick)",
    "Fretless Bass",
    "Slap Bass 1",
    "Slap Bass 2",
    "Synth Bass 1",
    "Synth Bass 2",
    "Violin",
    "Viola",
    "Cello",
    "Contrabass",
    "Tremulo Strings",
    "Pizzicato String",
    "Orchestral Harp",
    "Timpany",
    "String Ensemble 1",
    "String Ensemble 2",
    "Synth Strings 1",
    "SynthStrings 2",
    "Choir Aahs",
    "Voice Oohs",
    "Synth Voice",
    "Orchestra Hit",
    "Trumpet",
    "Trombone",
    "Tuba",
    "Muted Trumpet",
    "French Horn",
    "Brass Section",
    "Synth Brass 1",
    "Synth Brass 2",
    "Soprano Sax",
    "Alto Sax",
    "Tenor Sax",
    "Baritone Sax",
    "Oboe",
    "English Horn",
    "Bassoon",
    "Clarinet",
    "Piccolo",
    "Flute",
    "Recorder",
    "Pan Flute",
    "Bottle Blow",
    "Shakuhachi",
    "Whistle",
    "Ocarina",
    "Lead 1 squareea",
    "Lead 2 sawtooth",
    "Lead 3 calliope",
    "Lead 4 chiff",
    "Lead 5 charang",
    "Lead 6 voice",
    "Lead 7 fifths",
    "Lead 8 brass",
    "Pad 1 new age",
    "Pad 2 warm",
    "Pad 3 polysynth",
    "Pad 4 choir",
    "Pad 5 bowedpad",
    "Pad 6 metallic",
    "Pad 7 halo",
    "Pad 8 sweep",
    "FX 1 rain",
    "FX 2 soundtrack",
    "FX 3 crystal",
    "FX 4 atmosphere",
    "FX 5 brightness",
    "FX 6 goblins",
    "FX 7 echoes",
    "FX 8 sci-fi",
    "Sitar",
    "Banjo",
    "Shamisen",
    "Koto",
    "Kalimba",
    "Bagpipe",
    "Fiddle",
    "Shanai",
    "Tinkle Bell",
    "Agogo Bells",
    "Steel Drums",
    "Woodblock",
    "Taiko Drum",
    "Melodic Tom",
    "Synth Drum",
    "Reverse Cymbal",
    "Guitar FretNoise",
    "Breath Noise",
    "Seashore",
    "Bird Tweet",
    "Telephone",
    "Helicopter",
    "Applause/Noise",
    "Gunshot"
};

const char *MidiPercName[128] =
{
    "<Reserved 0>",
    "<Reserved 1>",
    "<Reserved 2>",
    "<Reserved 3>",
    "<Reserved 4>",
    "<Reserved 5>",
    "<Reserved 6>",
    "<Reserved 7>",
    "<Reserved 8>",
    "<Reserved 9>",
    "<Reserved 10>",
    "<Reserved 11>",
    "<Reserved 12>",
    "<Reserved 13>",
    "<Reserved 14>",
    "<Reserved 15>",
    "<Reserved 16>",
    "<Reserved 17>",
    "<Reserved 18>",
    "<Reserved 19>",
    "<Reserved 20>",
    "<Reserved 21>",
    "<Reserved 22>",
    "<Reserved 23>",
    "<Reserved 24>",
    "<Reserved 25>",
    "<Reserved 26>",
    "High Q",
    "Slap",
    "Scratch Push",
    "Scratch Pull",
    "Sticks",
    "Square Click",
    "Metronome Click",
    "Metronome Bell",
    "Ac Bass Drum",
    "Bass Drum 1",
    "Side Stick",
    "Acoustic Snare",
    "Hand Clap",
    "Electric Snare",
    "Low Floor Tom",
    "Closed High Hat",
    "High Floor Tom",
    "Pedal High Hat",
    "Low Tom",
    "Open High Hat",
    "Low-Mid Tom",
    "High-Mid Tom",
    "Crash Cymbal 1",
    "High Tom",
    "Ride Cymbal 1",
    "Chinese Cymbal",
    "Ride Bell",
    "Tambourine",
    "Splash Cymbal",
    "Cow Bell",
    "Crash Cymbal 2",
    "Vibraslap",
    "Ride Cymbal 2",
    "High Bongo",
    "Low Bongo",
    "Mute High Conga",
    "Open High Conga",
    "Low Conga",
    "High Timbale",
    "Low Timbale",
    "High Agogo",
    "Low Agogo",
    "Cabasa",
    "Maracas",
    "Short Whistle",
    "Long Whistle",
    "Short Guiro",
    "Long Guiro",
    "Claves",
    "High Wood Block",
    "Low Wood Block",
    "Mute Cuica",
    "Open Cuica",
    "Mute Triangle",
    "Open Triangle",
    "Shaker",
    "Jingle Bell",
    "Bell Tree",
    "Castanets",
    "Mute Surdu",
    "Open Surdu",
    "<Reserved 89>",
    "<Reserved 90>",
    "<Reserved 91>",
    "<Reserved 92>",
    "<Reserved 93>",
    "<Reserved 94>",
    "<Reserved 95>",
    "<Reserved 96>",
    "<Reserved 97>",
    "<Reserved 98>",
    "<Reserved 99>",
    "<Reserved 100>",
    "<Reserved 101>",
    "<Reserved 102>",
    "<Reserved 103>",
    "<Reserved 104>",
    "<Reserved 105>",
    "<Reserved 106>",
    "<Reserved 107>",
    "<Reserved 108>",
    "<Reserved 109>",
    "<Reserved 110>",
    "<Reserved 111>",
    "<Reserved 112>",
    "<Reserved 113>",
    "<Reserved 114>",
    "<Reserved 115>",
    "<Reserved 116>",
    "<Reserved 117>",
    "<Reserved 118>",
    "<Reserved 119>",
    "<Reserved 120>",
    "<Reserved 121>",
    "<Reserved 122>",
    "<Reserved 123>",
    "<Reserved 124>",
    "<Reserved 125>",
    "<Reserved 126>",
    "<Reserved 127>"
};
